name: CI

on:
  push:
    branches:
      - spring

jobs:
  test:
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: socialmediaproject

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Verify MariaDB connection
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done

    - name: Run tests
      run: ./mvnw test
